### PR TITLE
modified lots of ui design

### PR DESCRIPTION
**Pull request by ENDsoft233**
## 0x01 on ScheduleTable

 - support multi-themes
 - add '糖果' theme
 - - add border-radius and margin
 - - remove border
 - - modified coloring scheme

## 0x02 on ReservedClassesList

 - redesign the usage of CourseColor
 - change the text for the RemoveReservedClass button
 - bolden courseName text
 - add space between every credit and '学号' text
 - add CopyCourseId button for copying course id easierly

### CODE REVIEW

**Comment by ENDsoft233** [comment]
demo is available on https://xk.r-ay.cn/

**Comment by Errant404** [comment]
Instead of modifying the theme, it might be more popular to add a **switch theme function** (personal opinion, because I still like the original style🤪)

**Comment by chinggg** [comment]
Thanks for your work. Since I am no longer taking courses here, I am OK with any theme changes as long as they improve user experience.

**Comment by ENDsoft233** [comment]
@Errant404 ok now I have added the switch theme function :D

**Review by Errant404 — APPROVED** [review]
Good job ! 😍

**Review by chinggg — APPROVED** [review]
The CopyCourseId button should be useful. Theme switching is also a good job! Maybe we can support multiple semesters in the future as https://github.com/shuosc/shu-scheduling-helper/issues/34 proposed.

**Comment by ENDsoft233** [comment]
@chinggg i'm afraid to merge now because i don't know whether ci failed will influence build and deployment by github action after merging, does this repository deployed by github action automatically or not? （ci failed may due to using yarn 2 or some dependencies updated）

**Comment by ENDsoft233** [comment]
Adding 'engines ignore' due to ci failing and can't be fixed (https://github.com/vuejs/vue-cli/issues/7116) seems ok now. The deployment should be completed by anyone who has access.

**Comment by chinggg** [comment]
The website will be deployed by @ZKLlab

**Comment by ZKLlab** [comment]
@ENDsoft233 Thanks a lot for your valuable contribution to this project. I will review the code and get back to you as soon as possible.

**Review by ZKLlab — APPROVED** [review]
已 review，感谢 PR，主要有以下几点辛苦看看：

1. CopyCourseId.js、UseScheduleTableTheme.js 移到 src/mixins/common 目录下；
2. Storage 存储当前主题建议使用主题名称，如 classic 和 candy，同时需做好匹配不到主题的兜底；
3. 一些样式上的修改建议

**Review by ZKLlab — COMMENTED** [review]
scripts 里使用环境变量要用 cross-env 库支持 Windows 平台

**Review by ZKLlab — APPROVED** [review]
🎉 Thank you, I will merge it into the main branch. The pipeline will automatically build and deploy the website to the pre-production environment at https://pre.xk.shuosc.com. Please check if it meets the expected outcome and works properly. Once confirmed, I will release the website to the production environment.

**Comment by ENDsoft233** [comment]
I've checked the following changes and all seems ok.

 - theme selection and its storage
 - new CourseColor UI
 - CopyCourseId Function

It's time to release it, excited! XD
Thanks for your approval! @ZKLlab

**Comment by ZKLlab** [comment]
@ENDsoft233 Great! Thank you for confirming. I have now completed the deployment. If you encounter any issues or have further feedback, please do not hesitate to let me know. Also, you can check the deployment log of the production environment at https://github.com/shuosc/shu-scheduling-helper/deployments/activity_log?environment=production.

**Pull request merged**
